// Code generated by protoapi:go; DO NOT EDIT.

package nested

// Extra
type Extra struct {
	Message string `json:"message"`
}

func (r *Extra) GetMessage() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.Message
}
