/**
* This file is generated by 'protoapi'
* The file contains frontend API code that work with the library 'axios', therefore, it's required that 'axios' is installed in the project
* The generated code is written in TypeScript
* The code provides a basic usage for API call and may need adjustment according to specific project requirement and situation
* -------------------------------------------
* 该文件生成于protoapi
* 文件包含前端调用API的代码，并使用第三方库axios， 因此需要保证axios存在于项目中
* 文件内代码使用TypeScript
* 该生成文件只提供前端API调用基本代码，实际情况可能需要根据具体项目具体要求不同而作出更改
*/
import axios, { AxiosResponse, AxiosRequestConfig } from 'axios';
import {
    EnvListRequest,
    EnvListResponse,
    KVHistoryRequest,
    KVHistoryResponse,
    KeyListRequest,
    KeyListResponse,
    KeyValueListRequest,
    KeyValueListResponse,
    KeyValueRequest,
    KeyValueResponse,
    ProductListRequest,
    ProductListResponse,
    RegisterServiceRequest,
    RegisterServiceResponse,
    SearchKeyValueListRequest,
    ServiceListRequest,
    ServiceListResponse,
    ServiceSearchRequest,
    TagListRequest,
    TagListResponse,
    UpdateServiceRequest,
    UpdateServiceResponse,
    UploadProtoFileRequest,
    UploadProtoFileResponse,
    
} from './AppServiceObjs';
import { generateUrl, errorHandling } from './helper';

type Methods = "get" | "head" | "options" | "delete" | "post" | "put" | "patch"

let baseUrl = "http://192.168.115.60:8080";

const headers = {
    "X-Requested-With": "XMLHttpRequest"
};

export const SetBaseUrl: (url: string) => string = (url) => {
    baseUrl = url;
	return url;
}

export function setHeader(header: {[key: string]: string}) {
    return Object.assign(headers, header);
}

const axiosResponseHandler: <T = any>(response: AxiosResponse<T>) => T
= (response) => {
    const res_data = response.data
	if (typeof res_data === 'string') {
		try {
			return JSON.parse(res_data);
		} catch (e) {
			throw res_data;
		}
	}
    throw res_data;
}

const axiosHandler: (url: string, method: Methods, params: any) => Promise<any>
= (url, method, params) => {
    const config: AxiosRequestConfig = {
        transformResponse : (data) => data,
        headers,
    };
    const methodsAcceptData = ["post", "put", "patch"].includes(method)
    const axiosParams = methodsAcceptData ? params : undefined;
    if (!methodsAcceptData && !!params){
        config.params = params
    }
    const promise = methodsAcceptData
        ? axios[method as "post" | "put" | "patch"](url, axiosParams, config)
        : axios[method as "get" | "head" | "options" | "delete"].get(url, config);
    
    return promise
    .catch(err => {
        return errorHandling(err)
    })
    .then(res => {
        try {
            const resolved_data = axiosResponseHandler(res);
            return Promise.resolve(resolved_data);
        } catch (e) {
            return Promise.reject(res.data);
        }
    });
}

export function getEnv(params: EnvListRequest): Promise<EnvListResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "getEnv");
    return axiosHandler(url, "post", params) as Promise<EnvListResponse>;
}


export function registerService(params: RegisterServiceRequest): Promise<RegisterServiceResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "registerService");
    return axiosHandler(url, "post", params) as Promise<RegisterServiceResponse>;
}


export function updateService(params: UpdateServiceRequest): Promise<UpdateServiceResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "updateService");
    return axiosHandler(url, "post", params) as Promise<UpdateServiceResponse>;
}


export function uploadProtoFile(params: UploadProtoFileRequest): Promise<UploadProtoFileResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "uploadProtoFile");
    return axiosHandler(url, "post", params) as Promise<UploadProtoFileResponse>;
}


export function getTags(params: TagListRequest): Promise<TagListResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "getTags");
    return axiosHandler(url, "post", params) as Promise<TagListResponse>;
}


export function getProducts(params: ProductListRequest): Promise<ProductListResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "getProducts");
    return axiosHandler(url, "post", params) as Promise<ProductListResponse>;
}


export function getServices(params: ServiceListRequest): Promise<ServiceListResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "getServices");
    return axiosHandler(url, "post", params) as Promise<ServiceListResponse>;
}


export function searchServices(params: ServiceSearchRequest): Promise<ServiceListResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "searchServices");
    return axiosHandler(url, "post", params) as Promise<ServiceListResponse>;
}


export function getKeyList(params: KeyListRequest): Promise<KeyListResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "getKeyList");
    return axiosHandler(url, "post", params) as Promise<KeyListResponse>;
}


export function getKeyValueList(params: KeyValueListRequest): Promise<KeyValueListResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "getKeyValueList");
    return axiosHandler(url, "post", params) as Promise<KeyValueListResponse>;
}


export function searchKeyValueList(params: SearchKeyValueListRequest): Promise<KeyValueListResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "searchKeyValueList");
    return axiosHandler(url, "post", params) as Promise<KeyValueListResponse>;
}


export function updateKeyValue(params: KeyValueRequest): Promise<KeyValueResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "updateKeyValue");
    return axiosHandler(url, "post", params) as Promise<KeyValueResponse>;
}


export function fetchKeyHistory(params: KVHistoryRequest): Promise<KVHistoryResponse | never> {
    const url: string = generateUrl(baseUrl, "AppService", "fetchKeyHistory");
    return axiosHandler(url, "post", params) as Promise<KVHistoryResponse>;
}
