// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// EnvListResponse
type EnvListResponse struct {
	Envs []*Env `json:"envs"`
}

func (r *EnvListResponse) GetEnvs() []*Env {
	if r == nil {
		var zeroVal []*Env
		return zeroVal
	}
	return r.Envs
}
