// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// FieldError
type FieldError struct {
	FieldName string             `json:"fieldName"`
	ErrorType *ValidateErrorType `json:"errorType"`
}
