// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// Key
type Key struct {
	Key_id       int    `json:"key_id"`
	Key          string `json:"key"`
	DataType     string `json:"dataType"`
	DefaultValue string `json:"defaultValue"`
	IsWatched    bool   `json:"isWatched"`
}

func (r *Key) GetKey_id() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Key_id
}

func (r *Key) GetKey() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.Key
}

func (r *Key) GetDataType() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.DataType
}

func (r *Key) GetDefaultValue() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.DefaultValue
}

func (r *Key) GetIsWatched() bool {
	if r == nil {
		var zeroVal bool
		return zeroVal
	}
	return r.IsWatched
}
