// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// Key
type Key struct {
	Key_id       int    `json:"key_id"`
	Key          string `json:"key"`
	DataType     string `json:"dataType"`
	DefaultValue string `json:"defaultValue"`
	IsWatched    bool   `json:"isWatched"`
}
