// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// KeyValueRequest
type KeyValueRequest struct {
	Service_id int         `json:"service_id"`
	Key_values []*KeyValue `json:"key_values"`
}
