// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// KeyValue
type KeyValue struct {
	Key_id       int    `json:"key_id"`
	Key          string `json:"key"`
	DataType     string `json:"dataType"`
	DefaultValue string `json:"defaultValue"`
	IsWatched    bool   `json:"isWatched"`
	Value        string `json:"value"`
}
