// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// KVHistoryItem
type KVHistoryItem struct {
	Updated_value string `json:"updated_value"`
	Updated_date  string `json:"updated_date"`
	Updated_by    string `json:"updated_by"`
	Revision      int64  `json:"revision"`
}
