// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// RegisterServiceRequest
type RegisterServiceRequest struct {
	Env_id       int    `json:"env_id"`
	Product_id   string `json:"product_id"`
	Service_name string `json:"service_name"`
	Tags         []*Tag `json:"tags"`
	Desc         string `json:"desc"`
}
