// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// RegisterServiceResponse
type RegisterServiceResponse struct {
	Env_id       int    `json:"env_id"`
	Product_id   string `json:"product_id"`
	Service_id   int    `json:"service_id"`
	Service_name string `json:"service_name"`
}
