// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// SearchKeyValueListRequest
type SearchKeyValueListRequest struct {
	Key        string `json:"key"`
	Service_id int    `json:"service_id"`
	Env_id     int    `json:"env_id"`
}
