// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// ServiceListResponse
type ServiceListResponse struct {
	Services []*Service `json:"services"`
	Offset   int        `json:"offset"`
	Limit    int        `json:"limit"`
	Total    int        `json:"total"`
}
