// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// Service
type Service struct {
	Service_id   int    `json:"service_id"`
	Service_name string `json:"service_name"`
	Product_id   string `json:"product_id"`
	Product_name string `json:"product_name"`
	Desc         string `json:"desc"`
	Tags         []*Tag `json:"tags"`
}
