// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// UpdateServiceRequest
type UpdateServiceRequest struct {
	Service_id int    `json:"service_id"`
	Tags       []*Tag `json:"tags"`
	Desc       string `json:"desc"`
}
