// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// UploadProtoFileResponse
type UploadProtoFileResponse struct {
	Service_id int `json:"service_id"`
	Env_id     int `json:"env_id"`
	Key_count  int `json:"key_count"`
}
