// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// UploadProtoFileRequest
type UploadProtoFileRequest struct {
	Service_id int    `json:"service_id"`
	Env_id     int    `json:"env_id"`
	File       string `json:"file"`
}
