// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// UploadProtoFileRequest
type UploadProtoFileRequest struct {
	Service_id int    `json:"service_id"`
	Env_id     int    `json:"env_id"`
	File       string `json:"file"`
}

func (r *UploadProtoFileRequest) GetService_id() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Service_id
}

func (r *UploadProtoFileRequest) GetEnv_id() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Env_id
}

func (r *UploadProtoFileRequest) GetFile() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.File
}
