// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// UploadProtoFileResponse
type UploadProtoFileResponse struct {
	Service_id int `json:"service_id"`
	Env_id     int `json:"env_id"`
	Key_count  int `json:"key_count"`
}

func (r *UploadProtoFileResponse) GetService_id() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Service_id
}

func (r *UploadProtoFileResponse) GetEnv_id() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Env_id
}

func (r *UploadProtoFileResponse) GetKey_count() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Key_count
}
