// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

public abstract class AppServiceBase {
    @PostMapping("/AppService.getEnv")
    @ResponseBody
    public EnvListResponse getEnvPost(@RequestBody EnvListRequest in) {
        return getEnv(in);
    }

    abstract EnvListResponse getEnv(EnvListRequest in);
    
    @PostMapping("/AppService.registerService")
    @ResponseBody
    public RegisterServiceResponse registerServicePost(@RequestBody RegisterServiceRequest in) {
        return registerService(in);
    }

    abstract RegisterServiceResponse registerService(RegisterServiceRequest in);
    
    @PostMapping("/AppService.updateService")
    @ResponseBody
    public UpdateServiceResponse updateServicePost(@RequestBody UpdateServiceRequest in) {
        return updateService(in);
    }

    abstract UpdateServiceResponse updateService(UpdateServiceRequest in);
    
    @PostMapping("/AppService.uploadProtoFile")
    @ResponseBody
    public UploadProtoFileResponse uploadProtoFilePost(@RequestBody UploadProtoFileRequest in) {
        return uploadProtoFile(in);
    }

    abstract UploadProtoFileResponse uploadProtoFile(UploadProtoFileRequest in);
    
    @PostMapping("/AppService.getTags")
    @ResponseBody
    public TagListResponse getTagsPost(@RequestBody TagListRequest in) {
        return getTags(in);
    }

    abstract TagListResponse getTags(TagListRequest in);
    
    @PostMapping("/AppService.getProducts")
    @ResponseBody
    public ProductListResponse getProductsPost(@RequestBody ProductListRequest in) {
        return getProducts(in);
    }

    abstract ProductListResponse getProducts(ProductListRequest in);
    
    @PostMapping("/AppService.getServices")
    @ResponseBody
    public ServiceListResponse getServicesPost(@RequestBody ServiceListRequest in) {
        return getServices(in);
    }

    abstract ServiceListResponse getServices(ServiceListRequest in);
    
    @PostMapping("/AppService.searchServices")
    @ResponseBody
    public ServiceListResponse searchServicesPost(@RequestBody ServiceSearchRequest in) {
        return searchServices(in);
    }

    abstract ServiceListResponse searchServices(ServiceSearchRequest in);
    
    @PostMapping("/AppService.getKeyList")
    @ResponseBody
    public KeyListResponse getKeyListPost(@RequestBody KeyListRequest in) {
        return getKeyList(in);
    }

    abstract KeyListResponse getKeyList(KeyListRequest in);
    
    @PostMapping("/AppService.getKeyValueList")
    @ResponseBody
    public KeyValueListResponse getKeyValueListPost(@RequestBody KeyValueListRequest in) {
        return getKeyValueList(in);
    }

    abstract KeyValueListResponse getKeyValueList(KeyValueListRequest in);
    
    @PostMapping("/AppService.searchKeyValueList")
    @ResponseBody
    public KeyValueListResponse searchKeyValueListPost(@RequestBody SearchKeyValueListRequest in) {
        return searchKeyValueList(in);
    }

    abstract KeyValueListResponse searchKeyValueList(SearchKeyValueListRequest in);
    
    @PostMapping("/AppService.updateKeyValue")
    @ResponseBody
    public KeyValueResponse updateKeyValuePost(@RequestBody KeyValueRequest in) {
        return updateKeyValue(in);
    }

    abstract KeyValueResponse updateKeyValue(KeyValueRequest in);
    
    @PostMapping("/AppService.fetchKeyHistory")
    @ResponseBody
    public KVHistoryResponse fetchKeyHistoryPost(@RequestBody KVHistoryRequest in) {
        return fetchKeyHistory(in);
    }

    abstract KVHistoryResponse fetchKeyHistory(KVHistoryRequest in);
    
}
