// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class CommonError {
    private final GenericError genericError;
    private final AuthError authError;
    private final ValidateError validateError;
    private final BindError bindError;

    @JsonCreator
    public CommonError(@JsonProperty("genericError") GenericError genericError, @JsonProperty("authError") AuthError authError, @JsonProperty("validateError") ValidateError validateError, @JsonProperty("bindError") BindError bindError) {
        this.genericError = genericError;
        this.authError = authError;
        this.validateError = validateError;
        this.bindError = bindError;
    }

    public GenericError getGenericError() {
        return genericError;
    }
    public AuthError getAuthError() {
        return authError;
    }
    public ValidateError getValidateError() {
        return validateError;
    }
    public BindError getBindError() {
        return bindError;
    }
    
}
