// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class Env {
    private final int env_id;
    private final String env_name;

    @JsonCreator
    public Env(@JsonProperty("env_id") int env_id, @JsonProperty("env_name") String env_name) {
        this.env_id = env_id;
        this.env_name = env_name;
    }

    public int getEnv_id() {
        return env_id;
    }
    public String getEnv_name() {
        return env_name;
    }
    
}
