// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class EnvListResponse {
    private final List<Env> envs;

    @JsonCreator
    public EnvListResponse(@JsonProperty("envs") List<Env> envs) {
        this.envs = envs;
    }

    public List<Env> getEnvs() {
        return envs;
    }
    
}
