// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class Error {
    private final ErrorCode code;
    private final String message;

    @JsonCreator
    public Error(@JsonProperty("code") ErrorCode code, @JsonProperty("message") String message) {
        this.code = code;
        this.message = message;
    }

    public ErrorCode getCode() {
        return code;
    }
    public String getMessage() {
        return message;
    }
    
}
