// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class FieldError {
    private final String fieldName;
    private final ValidateErrorType errorType;

    @JsonCreator
    public FieldError(@JsonProperty("fieldName") String fieldName, @JsonProperty("errorType") ValidateErrorType errorType) {
        this.fieldName = fieldName;
        this.errorType = errorType;
    }

    public String getFieldName() {
        return fieldName;
    }
    public ValidateErrorType getErrorType() {
        return errorType;
    }
    
}
