// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class Key {
    private final int key_id;
    private final String key;
    private final String dataType;
    private final String defaultValue;
    private final boolean isWatched;

    @JsonCreator
    public Key(@JsonProperty("key_id") int key_id, @JsonProperty("key") String key, @JsonProperty("dataType") String dataType, @JsonProperty("defaultValue") String defaultValue, @JsonProperty("isWatched") boolean isWatched) {
        this.key_id = key_id;
        this.key = key;
        this.dataType = dataType;
        this.defaultValue = defaultValue;
        this.isWatched = isWatched;
    }

    public int getKey_id() {
        return key_id;
    }
    public String getKey() {
        return key;
    }
    public String getDataType() {
        return dataType;
    }
    public String getDefaultValue() {
        return defaultValue;
    }
    public boolean getIsWatched() {
        return isWatched;
    }
    
}
