// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class KeyListResponse {
    private final List<Key> keys;

    @JsonCreator
    public KeyListResponse(@JsonProperty("keys") List<Key> keys) {
        this.keys = keys;
    }

    public List<Key> getKeys() {
        return keys;
    }
    
}
