// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class KeyValueListResponse {
    private final List<KeyValue> key_values;

    @JsonCreator
    public KeyValueListResponse(@JsonProperty("key_values") List<KeyValue> key_values) {
        this.key_values = key_values;
    }

    public List<KeyValue> getKey_values() {
        return key_values;
    }
    
}
