// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class KeyValueRequest {
    private final int service_id;
    private final List<KeyValue> key_values;

    @JsonCreator
    public KeyValueRequest(@JsonProperty("service_id") int service_id, @JsonProperty("key_values") List<KeyValue> key_values) {
        this.service_id = service_id;
        this.key_values = key_values;
    }

    public int getService_id() {
        return service_id;
    }
    public List<KeyValue> getKey_values() {
        return key_values;
    }
    
}
