// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class KVHistoryResponse {
    private final List<KVHistoryItem> KVhistorys;

    @JsonCreator
    public KVHistoryResponse(@JsonProperty("KVhistorys") List<KVHistoryItem> KVhistorys) {
        this.KVhistorys = KVhistorys;
    }

    public List<KVHistoryItem> getKVhistorys() {
        return KVhistorys;
    }
    
}
