// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class KVHistoryRequest {
    private final int service_id;
    private final int key_id;

    @JsonCreator
    public KVHistoryRequest(@JsonProperty("service_id") int service_id, @JsonProperty("key_id") int key_id) {
        this.service_id = service_id;
        this.key_id = key_id;
    }

    public int getService_id() {
        return service_id;
    }
    public int getKey_id() {
        return key_id;
    }
    
}
