// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class ProductListResponse {
    private final List<Product> products;

    @JsonCreator
    public ProductListResponse(@JsonProperty("products") List<Product> products) {
        this.products = products;
    }

    public List<Product> getProducts() {
        return products;
    }
    
}
