// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class Product {
    private final String product_id;
    private final String product_name;

    @JsonCreator
    public Product(@JsonProperty("product_id") String product_id, @JsonProperty("product_name") String product_name) {
        this.product_id = product_id;
        this.product_name = product_name;
    }

    public String getProduct_id() {
        return product_id;
    }
    public String getProduct_name() {
        return product_name;
    }
    
}
