// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class ProductListRequest {
    private final int env_id;

    @JsonCreator
    public ProductListRequest(@JsonProperty("env_id") int env_id) {
        this.env_id = env_id;
    }

    public int getEnv_id() {
        return env_id;
    }
    
}
