// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class RegisterServiceResponse {
    private final int env_id;
    private final String product_id;
    private final int service_id;
    private final String service_name;

    @JsonCreator
    public RegisterServiceResponse(@JsonProperty("env_id") int env_id, @JsonProperty("product_id") String product_id, @JsonProperty("service_id") int service_id, @JsonProperty("service_name") String service_name) {
        this.env_id = env_id;
        this.product_id = product_id;
        this.service_id = service_id;
        this.service_name = service_name;
    }

    public int getEnv_id() {
        return env_id;
    }
    public String getProduct_id() {
        return product_id;
    }
    public int getService_id() {
        return service_id;
    }
    public String getService_name() {
        return service_name;
    }
    
}
