// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class RegisterServiceRequest {
    private final int env_id;
    private final String product_id;
    private final String service_name;
    private final List<Tag> tags;
    private final String desc;

    @JsonCreator
    public RegisterServiceRequest(@JsonProperty("env_id") int env_id, @JsonProperty("product_id") String product_id, @JsonProperty("service_name") String service_name, @JsonProperty("tags") List<Tag> tags, @JsonProperty("desc") String desc) {
        this.env_id = env_id;
        this.product_id = product_id;
        this.service_name = service_name;
        this.tags = tags;
        this.desc = desc;
    }

    public int getEnv_id() {
        return env_id;
    }
    public String getProduct_id() {
        return product_id;
    }
    public String getService_name() {
        return service_name;
    }
    public List<Tag> getTags() {
        return tags;
    }
    public String getDesc() {
        return desc;
    }
    
}
