// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class ServiceListResponse {
    private final List<Service> services;
    private final int offset;
    private final int limit;
    private final int total;

    @JsonCreator
    public ServiceListResponse(@JsonProperty("services") List<Service> services, @JsonProperty("offset") int offset, @JsonProperty("limit") int limit, @JsonProperty("total") int total) {
        this.services = services;
        this.offset = offset;
        this.limit = limit;
        this.total = total;
    }

    public List<Service> getServices() {
        return services;
    }
    public int getOffset() {
        return offset;
    }
    public int getLimit() {
        return limit;
    }
    public int getTotal() {
        return total;
    }
    
}
