// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class Service {
    private final int service_id;
    private final String service_name;
    private final String product_id;
    private final String product_name;
    private final String desc;
    private final List<Tag> tags;

    @JsonCreator
    public Service(@JsonProperty("service_id") int service_id, @JsonProperty("service_name") String service_name, @JsonProperty("product_id") String product_id, @JsonProperty("product_name") String product_name, @JsonProperty("desc") String desc, @JsonProperty("tags") List<Tag> tags) {
        this.service_id = service_id;
        this.service_name = service_name;
        this.product_id = product_id;
        this.product_name = product_name;
        this.desc = desc;
        this.tags = tags;
    }

    public int getService_id() {
        return service_id;
    }
    public String getService_name() {
        return service_name;
    }
    public String getProduct_id() {
        return product_id;
    }
    public String getProduct_name() {
        return product_name;
    }
    public String getDesc() {
        return desc;
    }
    public List<Tag> getTags() {
        return tags;
    }
    
}
