// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class UpdateServiceResponse {
    private final int service_id;
    private final List<Tag> tags;
    private final String desc;

    @JsonCreator
    public UpdateServiceResponse(@JsonProperty("service_id") int service_id, @JsonProperty("tags") List<Tag> tags, @JsonProperty("desc") String desc) {
        this.service_id = service_id;
        this.tags = tags;
        this.desc = desc;
    }

    public int getService_id() {
        return service_id;
    }
    public List<Tag> getTags() {
        return tags;
    }
    public String getDesc() {
        return desc;
    }
    
}
