// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class UploadProtoFileResponse {
    private final int service_id;
    private final int env_id;
    private final int key_count;

    @JsonCreator
    public UploadProtoFileResponse(@JsonProperty("service_id") int service_id, @JsonProperty("env_id") int env_id, @JsonProperty("key_count") int key_count) {
        this.service_id = service_id;
        this.env_id = env_id;
        this.key_count = key_count;
    }

    public int getService_id() {
        return service_id;
    }
    public int getEnv_id() {
        return env_id;
    }
    public int getKey_count() {
        return key_count;
    }
    
}
