// Code generated by protoapi; DO NOT EDIT.

package com.yoozoo.spring;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class UploadProtoFileRequest {
    private final int service_id;
    private final int env_id;
    private final String file;

    @JsonCreator
    public UploadProtoFileRequest(@JsonProperty("service_id") int service_id, @JsonProperty("env_id") int env_id, @JsonProperty("file") String file) {
        this.service_id = service_id;
        this.env_id = env_id;
        this.file = file;
    }

    public int getService_id() {
        return service_id;
    }
    public int getEnv_id() {
        return env_id;
    }
    public String getFile() {
        return file;
    }
    
}
