// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

type ErrorCode int

const (
	DefaultError  ErrorCode = 0
	GeneralError  ErrorCode = 1000
	DatabaseError ErrorCode = 1001
	EtcdError     ErrorCode = 1002
	SystemError   ErrorCode = 1003
)

func (code ErrorCode) String() string {
	names := map[ErrorCode]string{
		DefaultError:  "DefaultError",
		GeneralError:  "GeneralError",
		DatabaseError: "DatabaseError",
		EtcdError:     "EtcdError",
		SystemError:   "SystemError",
	}

	return names[code]
}

func (code ErrorCode) Code() int {
	return (int)(code)
}

func (code ErrorCode) IsDefaultError() bool {
	return code == DefaultError
}

func (code ErrorCode) IsGeneralError() bool {
	return code == GeneralError
}

func (code ErrorCode) IsDatabaseError() bool {
	return code == DatabaseError
}

func (code ErrorCode) IsEtcdError() bool {
	return code == EtcdError
}

func (code ErrorCode) IsSystemError() bool {
	return code == SystemError
}
