// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// KeyListResponse
type KeyListResponse struct {
	Keys []*Key `json:"keys"`
}

func (r *KeyListResponse) GetKeys() []*Key {
	if r == nil {
		var zeroVal []*Key
		return zeroVal
	}
	return r.Keys
}
