// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// KVHistoryResponse
type KVHistoryResponse struct {
	KVhistorys []*KVHistoryItem `json:"KVhistorys"`
}

func (r *KVHistoryResponse) GetKVhistorys() []*KVHistoryItem {
	if r == nil {
		var zeroVal []*KVHistoryItem
		return zeroVal
	}
	return r.KVhistorys
}
