// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// ProductListResponse
type ProductListResponse struct {
	Products []*Product `json:"products"`
}

func (r *ProductListResponse) GetProducts() []*Product {
	if r == nil {
		var zeroVal []*Product
		return zeroVal
	}
	return r.Products
}
