// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// RegisterServiceResponse
type RegisterServiceResponse struct {
	Env_id       int    `json:"env_id"`
	Product_id   string `json:"product_id"`
	Service_id   int    `json:"service_id"`
	Service_name string `json:"service_name"`
}

func (r *RegisterServiceResponse) GetEnv_id() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Env_id
}

func (r *RegisterServiceResponse) GetProduct_id() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.Product_id
}

func (r *RegisterServiceResponse) GetService_id() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Service_id
}

func (r *RegisterServiceResponse) GetService_name() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.Service_name
}
