// Code generated by protoapi:go; DO NOT EDIT.

package apisvr

// TagListResponse
type TagListResponse struct {
	Tags []*Tag `json:"tags"`
}

func (r *TagListResponse) GetTags() []*Tag {
	if r == nil {
		var zeroVal []*Tag
		return zeroVal
	}
	return r.Tags
}
