// Code generated by protoapi:go; DO NOT EDIT.

package calcsvrmain_without

// AddResp
type AddResp struct {
	Result int `json:"result"`
}

func (r *AddResp) GetResult() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Result
}
