// Code generated by protoapi:go; DO NOT EDIT.

package calcsvr

import (
	"github.com/labstack/echo"
	"github.com/yoozoo/protoapi/protoapigo"
)

// ExtendCalcService is the interface contains all the controllers
type ExtendCalcService interface {
	Minus(c echo.Context, req *AddReq) (resp *AddResp, bizError *AddError, err error)
}

func _minus_Handler(srv ExtendCalcService) echo.HandlerFunc {
	return func(c echo.Context) (err error) {
		req := new(AddReq)

		if err = c.Bind(req); err != nil {
			return c.JSON(500, err)
		}
		/*

		 */
		resp, bizError, err := srv.Minus(c, req)
		if err != nil {
			return c.String(500, err.Error())
		}
		if bizError != nil {
			return c.JSON(400, bizError)
		}

		return c.JSON(200, resp)
	}
}

// RegisterExtendCalcService is used to bind routers
func RegisterExtendCalcService(e *echo.Echo, srv ExtendCalcService) {
	RegisterExtendCalcServiceWithPrefix(e, srv, "")
}

// RegisterExtendCalcServiceWithPrefix is used to bind routers with custom prefix
func RegisterExtendCalcServiceWithPrefix(e *echo.Echo, srv ExtendCalcService, prefix string) {
	// switch to strict JSONAPIBinder, if using echo's DefaultBinder
	if _, ok := e.Binder.(*echo.DefaultBinder); ok {
		e.Binder = new(protoapigo.JSONAPIBinder)
	}
	e.POST(prefix+"/ExtendCalcService.minus", _minus_Handler(srv))
}
