// Code generated by protoapi:go; DO NOT EDIT.

package calcsvr

type ValidateErrorType int

const (
	INVALID_EMAIL  ValidateErrorType = 0
	FIELD_REQUIRED ValidateErrorType = 1
)

func (code ValidateErrorType) String() string {
	names := map[ValidateErrorType]string{
		INVALID_EMAIL:  "INVALID_EMAIL",
		FIELD_REQUIRED: "FIELD_REQUIRED",
	}

	return names[code]
}

func (code ValidateErrorType) Code() int {
	return (int)(code)
}

func (code ValidateErrorType) IsINVALID_EMAIL() bool {
	return code == INVALID_EMAIL
}

func (code ValidateErrorType) IsFIELD_REQUIRED() bool {
	return code == FIELD_REQUIRED
}
