// Code generated by protoapi:go; DO NOT EDIT.

package todolistsvr

// AddResp
type AddResp struct {
	Count int `json:"count"`
}

func (r *AddResp) GetCount() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Count
}
