// Code generated by protoapi:go; DO NOT EDIT.

package todolistsvr

// ListResp
type ListResp struct {
	Items []*Todo `json:"items"`
}

func (r *ListResp) GetItems() []*Todo {
	if r == nil {
		var zeroVal []*Todo
		return zeroVal
	}
	return r.Items
}
