// Code generated by protoapi:go; DO NOT EDIT.

package todolistsvr

// ListResp
type ListResp struct {
	Items []*todolist.Todo `json:"items"`
}

func (r *ListResp) GetItems() []*todolist.Todo {
	if r == nil {
		var zeroVal []*todolist.Todo
		return zeroVal
	}
	return r.Items
}
