// Code generated by protoapi:go; DO NOT EDIT.

package todolistsvr

// Todo
type Todo struct {
	Title string `json:"title"`
}

func (r *Todo) GetTitle() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.Title
}
