// Code generated by protoapi:go; DO NOT EDIT.

package calcsvrmain

// AuthError
type AuthError struct {
	Message string `json:"message"`
}

func (r *AuthError) GetMessage() string {
	if r == nil {
		var zeroVal string
		return zeroVal
	}
	return r.Message
}
