// Code generated by protoapi:go; DO NOT EDIT.

package calcsvr

// AddReq
type AddReq struct {
	X int `json:"x"`
	Y int `json:"y"`
}

func (r *AddReq) GetX() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.X
}

func (r *AddReq) GetY() int {
	if r == nil {
		var zeroVal int
		return zeroVal
	}
	return r.Y
}
