// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// BindError
type BindError struct {
	Message string `json:"message"`
}

func (r BindError) Validate() *ValidateError {
	errs := []*FieldError{}
	if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
