// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// FieldError
type FieldError struct {
    FieldName string `json:"fieldName"`
    ErrorType *ValidateErrorType `json:"errorType"`
}

func (r FieldError) Validate() *ValidateError {
    errs := []*FieldError{}
    if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
