// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// KeyListResponse
type KeyListResponse struct {
    Keys []*Key `json:"keys"`
}

func (r KeyListResponse) Validate() *ValidateError {
    errs := []*FieldError{}
    if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
