// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// KeyValueRequest
type KeyValueRequest struct {
	Service_id int `json:"service_id"`
	Key_values []*KeyValue `json:"key_values"`
}

func (r KeyValueRequest) Validate() *ValidateError {
	errs := []*FieldError{}
	if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
