// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// KeyValueListResponse
type KeyValueListResponse struct {
	Key_values []*KeyValue `json:"key_values"`
}

func (r KeyValueListResponse) Validate() *ValidateError {
	errs := []*FieldError{}
	if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
