// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// KVHistoryRequest
type KVHistoryRequest struct {
	Service_id int `json:"service_id"`
	Key_id int `json:"key_id"`
}

func (r KVHistoryRequest) Validate() *ValidateError {
	errs := []*FieldError{}
	if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
