// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// ProductListResponse
type ProductListResponse struct {
    Products []*Product `json:"products"`
}

func (r ProductListResponse) Validate() *ValidateError {
    errs := []*FieldError{}
    if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
