// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// Product
type Product struct {
	Product_id string `json:"product_id"`
	Product_name string `json:"product_name"`
}

func (r Product) Validate() *ValidateError {
	errs := []*FieldError{}
	if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
