// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// UpdateServiceRequest
type UpdateServiceRequest struct {
    Service_id int `json:"service_id"`
    Tags []*Tag `json:"tags"`
    Desc string `json:"desc"`
}

func (r UpdateServiceRequest) Validate() *ValidateError {
    errs := []*FieldError{}
    if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
