// Code generated by protoapi; DO NOT EDIT.

package yoozoo_protoconf_ts

// UploadProtoFileRequest
type UploadProtoFileRequest struct {
	Service_id int `json:"service_id"`
	Env_id int `json:"env_id"`
	File string `json:"file"`
}

func (r UploadProtoFileRequest) Validate() *ValidateError {
	errs := []*FieldError{}
	if len(errs) > 0 {
		return &ValidateError{Errors: errs}
	}
	return nil
}
